### ISSUE TITLE
Targeting net461

### ISSUE THREAD

**Issue by PiotrTecza** [davidfowl/TcpEcho#1]
I can't see socket.ReceiveAsync(memory, SocketFlags.None) overload in full framework, thus not able to pass writer.GetMemory(). How is this supposed to be used in NET461 Framework?

**Comment by gfoidl** [comment]
> How is this supposed to be used in NET461 Framework?

```c#
private static async Task FillPipeAsync(Socket socket, PipeWriter writer)
{
    const int minBuffersize = 512;

    while (true)
    {
        try
        {
            Memory<byte> memory = writer.GetMemory(minBuffersize);

#if NETCOREAPP2_1
            int bytesRead = await socket.ReceiveAsync(memory, SocketFlags.None);
#else
            int bytesRead = await socket.ReceiveAsync(memory.GetArray(), SocketFlags.None);
#endif
            if (bytesRead == 0) break;

            writer.Advance(bytesRead);
       // ...
}
```

`memory.GetArray()` is an [extension method](https://github.com/aspnet/KestrelHttpServer/blob/6c9d9f2b0c3193b5bb4c7f7182f116c0073f195f/src/Kestrel.Transport.Sockets/Internal/BufferExtensions.cs#L11)

Of course you can use other _#ifdefs_...

**Comment by springy76** [comment]
This sample does not even work when targeting net472 and using System.Memory 4.5.1.

So full .NET is already deprecated technology?

And why the extensions ` KestrelHttpServer/src/Kestrel.Transport.Sockets/Internal/BufferExtensions.cs` are available in plain vanilla netcoreapp which has nothing to do with aspnetcore?

Even using net472 you pretty fast get in a situation where a netstandard2.0 assembly just does not work.

**Comment by gfoidl** [comment]
> does not even work

The above code worked for me with _netcoreapp2.1_ and _net471_. Of course you have to adapt 
https://github.com/davidfowl/TcpEcho/blob/07ad4df181151850974219b8ebf434eee37778a4/src/Program.cs#L126
because this overload is new in _netcoreapp2.1_. 
Maybe something like
```c#
#if NETCOREAPP2_1
                string s = Encoding.UTF8.GetString(segment.Span);
#else
                ArraySegment<byte> array = segment.GetArray();
                string s = Encoding.UTF8.GetString(array.Array, array.Offset, array.Count);
#endif
                Console.Write(s);
```

> And why the extensions `KestrelHttpServer/src/Kestrel.Transport.Sockets/Internal/BufferExtensions.cs` are available in plain vanilla netcoreapp which has nothing to do with aspnetcore?

I can't follow to what you mean. 
But this extension was the first one I could remember / thought about to use for the issue here. There may be other ways too...

**Comment by davidfowl** [comment]
I can make the sample work on both.

**Comment by davidfowl** [comment]
Also PRs welcome

**Comment by scionwest** [comment]
> So full .NET is already deprecated technology?

That's a bit extreme @springy76. Just because a specific API doesn't exist in full .Net doesn't mean full .net is deprecated. I mean, there are far more APIs in full .Net than there are in netstandard or netcoreapp, so it's not like .net full framework is going away anytime soon.

**Comment by francisminu** [comment]
@gfoidl Hi Gunther
I have been trying to implement the System.IO.Pipelines using the reference in:
https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/

I have used:
var bytesRead = await socket.ReceiveAsync(memory, SocketFlags.None);
When there is no data to be read, the ReceiveAsync does not return. Any idea why this could be happening? 
In order to stop reading from the socket, it should go into bytesRead == 0, but when there is no data being sent to the socket, it just doesn't come back.
Any input is highly appreciated.

Thanks!

**Comment by gfoidl** [comment]
> When there is no data to be read, the ReceiveAsync does not return. Any idea why this could be happening?

This is the nature of TCP (transport). 
`socket.ReceiveAsync` gives you a `ValueTask<int>` that completes when "something" is read. 
This can be data, so the result will be > 0. 
This can be a disconnect (from the client), so the result will be = 0 -- in this case the loop is exited (https://github.com/davidfowl/TcpEcho/blob/2184c00be3e8d3229a4edd4a0adb07ae478a31cb/src/Program.cs#L55-L58) and the (pipe-) writer completes (https://github.com/davidfowl/TcpEcho/blob/2184c00be3e8d3229a4edd4a0adb07ae478a31cb/src/Program.cs#L77-L78).
So it works as expected.

Can you eloberate what exactely you mean? 
Note also that issues on GitHub are not the perfect place to get help, something like stackoverflow may be appropiate (please ignore this sentence if it doesn't match).
