### ISSUE TITLE
proper Cancellation?

### ISSUE THREAD

**Issue by springy76** [davidfowl/TcpEcho#2]
Currently the app freezes for seconds when clicking the red X of the console window -- which is nearly the same as a task kill.
How to stop `Socket.AcceptAsync` from "blocking" infinitely?

Further:
- what about proper disposing of IDisposables?
- async Main method does not contain a single await .. why not await ProcessLinesAsync?
- no .editorconfig so first contact with ctrl+k-d reformats everything

**Comment by gfoidl** [comment]
Keep in mind that this is an introductionary sample, not one that can and should be used in production directly. It's more or less a demo to get your feets wet with pipelines.
If this demo would be productized, then it would be too big for an intro. 

> Currently the app freezes for seconds when clicking the red X of the console window

In this demo there is no unbind on the socket, etc. and nothing that stops the accept-loop
https://github.com/davidfowl/TcpEcho/blob/07ad4df181151850974219b8ebf434eee37778a4/src/Program.cs#L22-L26
You could run this server in a [generic host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host), and leverage _cancellation_ as well as proper disposing.
But, as said before, this would be too much for an intro...

> async Main method does not contain a single await

Here it is: https://github.com/davidfowl/TcpEcho/blob/07ad4df181151850974219b8ebf434eee37778a4/src/Program.cs#L24

> .. why not await ProcessLinesAsync?

Imagine 
https://github.com/davidfowl/TcpEcho/blob/07ad4df181151850974219b8ebf434eee37778a4/src/Program.cs#L25
would be written as
```c#
await ProcessLinesAsync(socket);
```
what would happen? 
1. The accept-loop asynchronously awaits a client-connection https://github.com/davidfowl/TcpEcho/blob/07ad4df181151850974219b8ebf434eee37778a4/src/Program.cs#L24
1. `ProcessLinesAsync` is "started" for that client, the accept-loop asynchronously awaits `ProcessLinesAsync` to be completed
1. `ProcessLinesAsync` will complete only when _reading_ and _writing_ are done https://github.com/davidfowl/TcpEcho/blob/07ad4df181151850974219b8ebf434eee37778a4/src/Program.cs#L37
1. goto point 1

So this would handle one client at a time and when the one is done, the next client is handled.
Not very scalable.

With the implementation as is, the following happens:
1. The accept-loop asynchronously awaits a client-connection
1. `ProcessLinesAsync` is "started" for that client, the returning `Task` is thrown away, because we don't want to await it
1. goto point 1

So when `ProcessLinesAsync` is started -- or to be more precise, when it yields the first time (`await`) -- the accept-loop can await for other clients. Quite more scalable.
Mature implementations like Kestrel have a [more complex accept-loop](https://github.com/aspnet/KestrelHttpServer/blob/5e4fae2573fc2e6be9bb708931fa12468cb43313/src/Kestrel.Transport.Sockets/SocketTransport.cs#L146-L188).

**Comment by springy76** [comment]
Alright, was not aware that this would become single-user then.

But the most important question is still unanswered:
How to cancel `await listenSocket.AcceptAsync();` in a safe way?

**Comment by gfoidl** [comment]
Have a look at [a generic host implementation of this demo](https://github.com/gfoidl/TcpEcho/tree/ffded446d78a6c528fc5295615a093bd38c50277/src).

Note that this is still a demo with lots of room for improvement (like proper connection-handling, exception-handling, and so on and even more refactoring -- here `TcpEchoServer` is as much as possible a copy & past from the original demo). If you'd like to see how to handle the things in a correct way, you can drive inspriation from [Kestrel](https://github.com/aspnet/KestrelHttpServer/blob/5e4fae2573fc2e6be9bb708931fa12468cb43313/src/Kestrel.Transport.Sockets/SocketTransport.cs)

PS: For an intro this is too much code, so I won't submit an PR. Maybe we can create a ReadMe here that points to the blog post and links "enhanced" demos of this.

**Comment by springy76** [comment]
So disposing the `Socket` instance on a random thread and catching exceptions selectively by observing an unloading state field is the most safe way? IMHO this `AcceptAsync` method should natively support `CancellationToken`. The same goes for `UdpClient.ReceiveAsync()`.
Any async method not accepting a `CancellationToken` looks smelly to me.

**Comment by gfoidl** [comment]
> Any async method not accepting a `CancellationToken` looks smelly to me.

Agreed.

I believe the problems here with accepting a `CancellationToken` are rooted in how managed code and the operating system interact on the sockets. The managed part is more or less just a wrapper for the os-native Berkeley socket, so cancelling on the managed side has to cancel in a proper way on the os-side too, and this seems to be not so trivial.

https://github.com/dotnet/corefx/issues/5749 is one issue that tracks this desire.

**Comment by GSPP** [comment]
Adding two related issues:

* https://github.com/dotnet/corefx/issues/5749 Add a clean way to cancel a long-running Socket operation (e.g. accept or connect)
* https://github.com/dotnet/corefx/issues/9698 Add reliable timeouts to socket operations

**Comment by davidfowl** [comment]
Send me a pull request 😄
